import type { Pool } from 'pg'
import { PDFParse } from 'pdf-parse'
import { extractRawText } from 'mammoth'
import type { RecruitmentJobInput, RecruitmentUpload } from './recruitment-input.js'
import { screenResume } from './recruitment-screening.js'
const iso=(v:string|Date)=>v instanceof Date?v.toISOString():v
async function resumeText(upload: RecruitmentUpload): Promise<string> { if (upload.text) return upload.text; const data=Buffer.from(upload.base64,'base64'); const extension=upload.fileName.split('.').at(-1)?.toLowerCase(); try { if(extension==='pdf'){const parser=new PDFParse({data});try{return (await parser.getText()).text.slice(0,300_000)}finally{await parser.destroy()}} if(extension==='docx') return (await extractRawText({buffer:data})).value.slice(0,300_000) } catch { /* 保留原文件并交由人工复核。 */ } return '' }
export class RecruitmentRepository { constructor(private readonly pool: Pool) {}
 async jobs(){const r=await this.pool.query(`SELECT id::text,title,department,status,created_at,updated_at,(SELECT count(*)::text FROM recruitment_candidates c WHERE c.job_id=j.id) candidates FROM recruitment_jobs j ORDER BY status,title,id DESC`);return r.rows.map(x=>({id:x.id,title:x.title,department:x.department,status:x.status,createdAt:iso(x.created_at),updatedAt:iso(x.updated_at),candidates:Number(x.candidates)}))}
 async createJob(input:RecruitmentJobInput,accountId:string){const r=await this.pool.query(`INSERT INTO recruitment_jobs (title,department,responsibilities,required_conditions,preferred_conditions,exclusion_conditions,work_location,education_requirement,experience_requirement,created_by_account_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id::text`,[input.title,input.department,input.responsibilities,input.requiredConditions,input.preferredConditions,input.exclusionConditions,input.workLocation,input.educationRequirement,input.experienceRequirement,accountId]);return String(r.rows[0]!.id)}
 async job(id:string){const r=await this.pool.query(`SELECT id::text,title,department,responsibilities,required_conditions "requiredConditions",preferred_conditions "preferredConditions",exclusion_conditions "exclusionConditions",work_location "workLocation",education_requirement "educationRequirement",experience_requirement "experienceRequirement",status FROM recruitment_jobs WHERE id=$1`,[id]);return r.rows[0]??null}
 async removeJob(id:string){const r=await this.pool.query('DELETE FROM recruitment_jobs WHERE id=$1',[id]);return (r.rowCount??0)>0}
 async candidates(jobId:string){const r=await this.pool.query(`SELECT id::text,file_name "fileName",mime_type "mimeType",screening_bucket "bucket",screening_reasons "reasons",status,candidate_stage "candidateStage",candidate_notes "candidateNotes",created_at "createdAt" FROM recruitment_candidates WHERE job_id=$1 ORDER BY CASE screening_bucket WHEN 'priority' THEN 1 WHEN 'review' THEN 2 ELSE 3 END,id DESC`,[jobId]);return r.rows}
 async candidatePool(){const r=await this.pool.query(`SELECT c.id::text,c.job_id::text "jobId",c.file_name "fileName",c.mime_type "mimeType",c.candidate_stage "candidateStage",c.candidate_notes "candidateNotes",c.updated_at "updatedAt",j.title "jobTitle",j.department "jobDepartment" FROM recruitment_candidates c JOIN recruitment_jobs j ON j.id=c.job_id WHERE c.candidate_stage<>'none' ORDER BY CASE c.candidate_stage WHEN 'to_contact' THEN 1 WHEN 'interview_scheduled' THEN 2 WHEN 'interviewing' THEN 3 WHEN 'pending_offer' THEN 4 WHEN 'hired' THEN 5 ELSE 6 END,c.updated_at DESC,c.id DESC`);return r.rows}
 async upload(jobId:string,uploads:readonly RecruitmentUpload[],accountId:string){const job=await this.job(jobId);if(!job) return 0;const client=await this.pool.connect();try{await client.query('BEGIN');for(const upload of uploads){const text=await resumeText(upload);const outcome=screenResume(job,text);await client.query(`INSERT INTO recruitment_candidates (job_id,file_name,mime_type,file_data,extracted_text,screening_bucket,screening_reasons,uploaded_by_account_id,updated_by_account_id) VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$8)`,[jobId,upload.fileName,upload.mimeType,Buffer.from(upload.base64,'base64'),text,outcome.bucket,JSON.stringify(outcome.reasons),accountId])}await client.query('COMMIT');return uploads.length}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
 async setStatus(jobId:string,ids:readonly string[],status:'eliminated'|'restored',accountId:string){const r=await this.pool.query(`UPDATE recruitment_candidates SET status=$3,updated_by_account_id=$4,updated_at=now() WHERE job_id=$1 AND id=ANY($2::bigint[])`,[jobId,ids,status,accountId]);return r.rowCount??0}
 async setCandidate(jobId:string,id:string,stage:string,notes:string,accountId:string){const r=await this.pool.query(`UPDATE recruitment_candidates SET candidate_stage=$3,candidate_notes=$4,updated_by_account_id=$5,updated_at=now() WHERE job_id=$1 AND id=$2`,[jobId,id,stage,notes,accountId]);return (r.rowCount??0)>0}
 async remove(jobId:string,id:string){const r=await this.pool.query('DELETE FROM recruitment_candidates WHERE job_id=$1 AND id=$2',[jobId,id]);return (r.rowCount??0)>0}
 async file(jobId:string,id:string){const r=await this.pool.query<{file_name:string,mime_type:string,file_data:Buffer}>('SELECT file_name,mime_type,file_data FROM recruitment_candidates WHERE job_id=$1 AND id=$2',[jobId,id]);return r.rows[0]??null}
}
