import { RotateCcw, Save, X } from 'lucide-react'
import { useEffect, useState } from 'react'

export type CandidateStage = 'none'|'to_contact'|'interview_scheduled'|'interviewing'|'pending_offer'|'hired'|'declined'
export type PipelineCandidate = { id:string; jobId:string; fileName:string; candidateStage:CandidateStage; candidateNotes:string; jobTitle:string; jobDepartment:string }
type Eliminated = { id:string; jobId:string; fileName:string; jobTitle:string; jobDepartment:string; reasons:string[] }

export function CandidatePool({ candidates, onChange, onClose }: { readonly candidates:readonly PipelineCandidate[]; readonly onChange:(candidate:PipelineCandidate, stage:CandidateStage, notes:string) => Promise<void>; readonly onClose:(candidate:PipelineCandidate) => Promise<void> }) {
  const [eliminated, setEliminated] = useState<Eliminated[]>([])
  const load = () => fetch('/api/recruitment/eliminated',{credentials:'same-origin'}).then(response => response.ok ? response.json() : { candidates:[] }).then(data => setEliminated(data.candidates))
  useEffect(() => { void load() }, [])
  const restore = async (candidate:Eliminated) => { await fetch(`/api/recruitment/jobs/${candidate.jobId}/candidates/${candidate.id}/status`,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({ids:[candidate.id],status:'restored'})}); await load() }
  return <><section className="recruitment__pipeline"><header><div><h2>候选名单</h2><p>集中推进已标记候选人的招聘阶段与跟进记录。</p></div><span>{candidates.length} 人</span></header><div className="recruitment__pipeline-list">{candidates.length ? candidates.map(candidate => <Row key={candidate.id} candidate={candidate} onChange={onChange} onClose={onClose}/>) : <p className="recruitment__none">暂无候选人</p>}</div></section><section className="recruitment__pipeline"><header><div><h2>淘汰名单</h2><p>已淘汰简历保留在此，可恢复至原岗位。</p></div><span>{eliminated.length} 人</span></header><div className="recruitment__pipeline-list">{eliminated.length ? eliminated.map(candidate => <article className="recruitment__pipeline-row" key={candidate.id}><div className="recruitment__pipeline-person"><strong>{candidate.fileName}</strong><span>{candidate.jobTitle}{candidate.jobDepartment ? ` · ${candidate.jobDepartment}` : ''}</span></div><button onClick={() => void restore(candidate)}><RotateCcw size={14}/>恢复</button></article>) : <p className="recruitment__none">暂无淘汰记录</p>}</div></section></>
}
function Row({ candidate, onChange, onClose }: { readonly candidate:PipelineCandidate; readonly onChange:(candidate:PipelineCandidate, stage:CandidateStage, notes:string) => Promise<void>; readonly onClose:(candidate:PipelineCandidate) => Promise<void> }) { let stage = candidate.candidateStage; let notes = candidate.candidateNotes; return <article className="recruitment__pipeline-row"><div className="recruitment__pipeline-person"><strong>{candidate.fileName}</strong><span>{candidate.jobTitle}{candidate.jobDepartment ? ` · ${candidate.jobDepartment}` : ''}</span></div><select defaultValue={stage} onChange={event => { stage=event.target.value as CandidateStage }}><option value="to_contact">待联系</option><option value="interview_scheduled">已约面</option><option value="interviewing">面试中</option><option value="pending_offer">待录用</option><option value="hired">已录用</option><option value="declined">不考虑</option></select><textarea defaultValue={notes} placeholder="填写跟进备注" onChange={event => { notes=event.target.value }}/><div className="recruitment__pipeline-actions"><button onClick={() => void onChange(candidate,stage,notes)}><Save size={14}/>保存</button><button onClick={() => void onClose(candidate)}><X size={15}/>撤回</button></div></article> }
