import { BriefcaseBusiness, Eye, FileUp, Plus, RotateCcw, Trash2, UserRoundPlus, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { ModuleProps } from '../../app/types'
import { CandidatePool, type CandidateStage, type PipelineCandidate } from './candidates/CandidatePool'
import './recruitment.css'
import './recruitment-refinements.css'

type Job = { id:string; title:string; department:string; status:'open'|'closed'; candidates:number }
type JobDetails = Job & { responsibilities:string; requiredConditions:string; preferredConditions:string; exclusionConditions:string; workLocation:string; educationRequirement:string; experienceRequirement:string }
type Candidate = { id:string; fileName:string; mimeType:string; bucket:'priority'|'review'|'unrelated'; reasons:string[]; status:'pending'|'eliminated'|'restored'; candidateStage:CandidateStage; candidateNotes:string }
type JobDraft = Omit<JobDetails, 'id'|'status'|'candidates'>
const empty:JobDraft = { title:'', department:'', responsibilities:'', requiredConditions:'', preferredConditions:'', exclusionConditions:'', workLocation:'', educationRequirement:'', experienceRequirement:'' }
const detailFields:[keyof Omit<JobDetails, 'id'|'title'|'department'|'status'|'candidates'>,string][] = [['responsibilities','岗位职责'],['requiredConditions','必需条件'],['preferredConditions','加分条件'],['exclusionConditions','排除条件'],['workLocation','工作地点'],['educationRequirement','学历要求'],['experienceRequirement','工作经验要求']]

async function api<T>(path:string, init:RequestInit = {}) { const response = await fetch(path, { ...init, credentials:'same-origin', headers:{ 'content-type':'application/json', ...(init.headers ?? {}) } }); if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(typeof body.error === 'string' ? body.error : `请求失败（${response.status}）`) }; return response.status === 204 ? undefined as T : await response.json() as T }
function base64(file:File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => typeof reader.result === 'string' ? resolve(reader.result.split(',').at(-1) ?? '') : reject(new Error('读取简历失败。')); reader.onerror = () => reject(new Error('读取简历失败。')); reader.readAsDataURL(file) }) }

export function RecruitmentManagementModule(_props:ModuleProps) {
  const [jobs, setJobs] = useState<Job[]>([]); const [selected, setSelected] = useState<Job | null>(null); const [candidates, setCandidates] = useState<Candidate[]>([]); const [pipeline, setPipeline] = useState<PipelineCandidate[]>([])
  const [screen, setScreen] = useState<'jobs'|'pipeline'|'eliminated'>('jobs'); const [pipelineTab, setPipelineTab] = useState<'candidate'|'eliminated'>('candidate'); const [draft, setDraft] = useState<JobDraft | null>(null); const [details, setDetails] = useState<JobDetails | null>(null); const [message, setMessage] = useState(''); const [fileBusy, setFileBusy] = useState(false); const [fileInput, setFileInput] = useState<HTMLInputElement | null>(null)
  const load = () => api<{ jobs:Job[] }>('/api/recruitment/jobs').then(data => setJobs(data.jobs)).catch(error => setMessage(error.message))
  const loadCandidates = (id:string) => api<{ candidates:Candidate[] }>(`/api/recruitment/jobs/${id}/candidates`).then(data => setCandidates(data.candidates.filter(candidate => candidate.status !== 'eliminated' && candidate.candidateStage === 'none'))).catch(error => setMessage(error.message))
  const loadPipeline = () => api<{ candidates:PipelineCandidate[] }>('/api/recruitment/candidates').then(data => setPipeline(data.candidates)).catch(error => setMessage(error.message))
  useEffect(() => { load(); loadPipeline() }, [])
  function choose(job:Job) { setScreen('jobs'); setSelected(job); setCandidates([]); loadCandidates(job.id) }
  async function view(job:Job) { try { setDetails((await api<{ job:JobDetails }>(`/api/recruitment/jobs/${job.id}`)).job) } catch (error) { setMessage(error instanceof Error ? error.message : String(error)) } }
  async function create() { if (!draft) return; try { const data = await api<{ id:string }>('/api/recruitment/jobs', { method:'POST', body:JSON.stringify(draft) }); const job = { id:data.id, title:draft.title, department:draft.department, status:'open' as const, candidates:0 }; setDraft(null); await load(); setMessage('岗位已创建。'); choose(job) } catch (error) { setMessage(error instanceof Error ? error.message : String(error)) } }
  async function removeJob(job:Job) { if (!confirm(`确认删除“${job.title}”及其全部简历记录？此操作不可恢复。`)) return; try { await api(`/api/recruitment/jobs/${job.id}`, { method:'DELETE' }); if (selected?.id === job.id) { setSelected(null); setCandidates([]) }; if (details?.id === job.id) setDetails(null); await load(); await loadPipeline(); setMessage('岗位及其简历记录已删除。') } catch (error) { setMessage(error instanceof Error ? error.message : String(error)) } }
  async function upload(files:FileList | null) { if (!selected || !files?.length) return; const list = [...files]; if (list.some(file => file.size > 5 * 1024 * 1024)) { setMessage('单份简历不能超过 5 MB。'); return }; setFileBusy(true); try { let uploaded = 0; for (const file of list) { const payload = { fileName:file.name, mimeType:file.type || 'application/octet-stream', base64:await base64(file) }; const result = await api<{ count:number }>(`/api/recruitment/jobs/${selected.id}/candidates`, { method:'POST', body:JSON.stringify({ files:[payload] }) }); uploaded += result.count }; setMessage(`已上传 ${uploaded} 份简历，筛选结果已生成。`); loadCandidates(selected.id); load() } catch (error) { setMessage(error instanceof Error ? error.message : String(error)) } finally { setFileBusy(false); if (fileInput) fileInput.value = '' } }
  async function status(ids:string[], value:'eliminated'|'restored') { if (!selected || !ids.length) return; if (value === 'eliminated' && !confirm(`确认淘汰 ${ids.length} 份简历？可在已淘汰中恢复。`)) return; await api(`/api/recruitment/jobs/${selected.id}/candidates/${ids[0]}/status`, { method:'POST', body:JSON.stringify({ ids, status:value }) }); loadCandidates(selected.id); loadPipeline(); setMessage(value === 'eliminated' ? '已更新为淘汰。' : '已恢复至人工复核。') }
  async function updateCandidate(candidate:Pick<PipelineCandidate,'id'|'jobId'>, stage:CandidateStage, notes:string) { await api(`/api/recruitment/jobs/${candidate.jobId}/candidates/${candidate.id}/candidate`, { method:'POST', body:JSON.stringify({ stage, notes }) }); if (selected?.id === candidate.jobId) loadCandidates(candidate.jobId); await loadPipeline(); setMessage(stage === 'none' ? '已撤回候选。' : '候选状态已更新。') }
  async function markCandidate(candidate:Candidate) { if (!selected) return; await updateCandidate({ id:candidate.id, jobId:selected.id },'to_contact',candidate.candidateNotes); setMessage('已加入候选名单。') }
  async function removeCandidate(id:string) { if (!selected || !confirm('确认永久删除这份简历及其筛选记录？')) return; await api(`/api/recruitment/jobs/${selected.id}/candidates/${id}`, { method:'DELETE' }); loadCandidates(selected.id); load(); loadPipeline(); setMessage('简历已删除。') }
  const buckets:[Candidate['bucket'], string][] = [['priority','优先查看'], ['review','人工复核'], ['unrelated','明显不匹配']]
  return <div className="recruitment module-page"><header><div><h1>招聘管理</h1><p>按岗位批量筛选简历，保留人工确认与恢复入口。</p></div><div className="recruitment__top-actions"><button className={screen === 'jobs' ? 'is-selected' : ''} onClick={() => setScreen('jobs')}>岗位简历</button><button className={screen === 'pipeline' && pipelineTab === 'candidate' ? 'is-selected' : ''} onClick={() => { setScreen('pipeline'); setPipelineTab('candidate'); loadPipeline(); setTimeout(() => window.dispatchEvent(new CustomEvent('recruitment:tab',{detail:'candidate'})),0) }}>候选名单</button><button className={screen === 'pipeline' && pipelineTab === 'eliminated' ? 'is-selected' : ''} onClick={() => { setScreen('pipeline'); setPipelineTab('eliminated'); setTimeout(() => window.dispatchEvent(new CustomEvent('recruitment:tab',{detail:'eliminated'})),0) }}>淘汰名单</button><button className="recruitment__primary" onClick={() => setDraft(empty)}><Plus size={16}/>新建岗位</button></div></header>{message && <p className="recruitment__message">{message}</p>}
    {screen === 'pipeline' ? <CandidatePool candidates={pipeline} onChange={updateCandidate} onClose={candidate => updateCandidate(candidate,'none','')}/> : <main><aside><h2>招聘岗位</h2>{jobs.map(job => <div className={`recruitment__job ${selected?.id === job.id ? 'is-active' : ''}`} key={job.id}><button className="recruitment__job-main" onClick={() => choose(job)}><strong>{job.title}</strong><span>{job.department || '未填写部门'} · {job.candidates} 份简历</span></button><div className="recruitment__job-actions"><button type="button" onClick={() => void view(job)} title="查看岗位要求"><Eye size={15}/></button><button type="button" onClick={() => void removeJob(job)} title="删除岗位"><X size={16}/></button></div></div>)}{!jobs.length && <p>暂无岗位，请先新建。</p>}</aside><section className="recruitment__content">{!selected ? <div className="recruitment__empty"><BriefcaseBusiness size={28}/><p>选择或新建一个岗位后开始筛选简历。</p></div> : <><header><div><h2>{selected.title}</h2><span>{selected.department || '未填写部门'}</span></div><button className="recruitment__upload" disabled={fileBusy} onClick={() => fileInput?.click()}><FileUp size={16}/>{fileBusy ? '上传中…' : '上传简历'}</button><input ref={setFileInput} type="file" multiple accept=".pdf,.doc,.docx" onChange={event => void upload(event.target.files)}/></header><div className="recruitment__buckets">{buckets.map(([bucket, label]) => { const items = candidates.filter(candidate => candidate.bucket === bucket); return <section className="recruitment__bucket" key={bucket}><header><h3>{label}<small>{items.length}</small></h3>{bucket === 'unrelated' && items.some(item => item.status !== 'eliminated') && <button onClick={() => void status(items.filter(item => item.status !== 'eliminated').map(item => item.id), 'eliminated')}>一键淘汰</button>}</header><div className="recruitment__bucket-body">{items.map(candidate => <article className={candidate.status === 'eliminated' ? 'is-eliminated' : ''} key={candidate.id}><div><a href={`/api/recruitment/jobs/${selected.id}/candidates/${candidate.id}/file`} target="_blank" rel="noreferrer">{candidate.fileName}</a><p>{candidate.reasons.join(' ')}</p></div><div>{candidate.candidateStage === 'none' && candidate.status !== 'eliminated' && <button className="recruitment__candidate" onClick={() => void markCandidate(candidate)}><UserRoundPlus size={14}/>候选</button>}{candidate.status === 'eliminated' ? <button onClick={() => void status([candidate.id], 'restored')}><RotateCcw size={14}/>恢复</button> : <button className="is-danger" onClick={() => void status([candidate.id], 'eliminated')}>淘汰</button>}<button className="recruitment__delete" onClick={() => void removeCandidate(candidate.id)} title="永久删除"><Trash2 size={15}/></button></div></article>)}{!items.length && <p className="recruitment__none">暂无简历</p>}</div></section> })}</div></>}</section></main>}
    {draft && <div className="recruitment__modal"><button className="recruitment__backdrop" onClick={() => setDraft(null)}/><section><header><h2>新建招聘岗位</h2><button onClick={() => setDraft(null)}><X size={18}/></button></header>{Object.entries({ title:'岗位名称', department:'招聘部门', responsibilities:'岗位职责', requiredConditions:'必需条件（用顿号或换行分隔）', preferredConditions:'加分条件', exclusionConditions:'明确不考虑的情况', workLocation:'工作地点', educationRequirement:'学历要求', experienceRequirement:'工作经验要求' }).map(([key,label]) => <label key={key}>{label}<textarea rows={key === 'responsibilities' ? 4 : 2} value={draft[key as keyof JobDraft]} onChange={event => setDraft({ ...draft, [key]:event.target.value })}/></label>)}<footer><button onClick={() => setDraft(null)}>取消</button><button className="recruitment__primary" onClick={() => void create()}>创建岗位</button></footer></section></div>}
    {details && <div className="recruitment__modal"><button className="recruitment__backdrop" onClick={() => setDetails(null)}/><section className="recruitment__requirements"><header><div><h2>{details.title}</h2><p>{details.department || '未填写部门'}</p></div><button onClick={() => setDetails(null)}><X size={18}/></button></header>{detailFields.map(([key,label]) => <div key={key}><h3>{label}</h3><p>{details[key] || '未填写'}</p></div>)}</section></div>}
  </div>
}
